apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # RDS MySQL credentials - Serão substituídos pelo pipeline do GitHub Actions
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  # DocumentDB MongoDB credentials - Serão substituídos pelo pipeline do GitHub Actions
  MONGO_USER: "${MONGO_USER}"
  MONGO_PASSWORD: "${MONGO_PASSWORD}"
  MONGO_HOST: "${MONGO_HOST}"
  MONGO_DB: "${MONGO_DB}"
  # JWT Secret - Substitua por um valor seguro
  JWT_SECRET: "${JWT_SECRET}"
  NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
  # Email service credentials - Substitua pelos valores reais do serviço de email
  EMAIL_HOST: "smtp.server.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "your_email@example.com"
  EMAIL_PASS: "your_email_password"
  EMAIL_FROM: "your_email@example.com"