apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # RDS MySQL credentials - Substitua pelos valores reais do projeto 3 (Infra DB)
  DB_USERNAME: rds-username
  DB_PASSWORD: rds-password
  # DocumentDB MongoDB credentials - Substitua pelos valores reais do projeto 3 (Infra DB)
  MONGO_USER: docdb-username
  MONGO_PASS: docdb-password
  # JWT Secret - Substitua por um valor seguro
  JWT_SECRET: AUTH_JWT_TECH_CHALLENGE_FIAP
  NEW_RELIC_LICENSE_KEY: 08aac475f512958263f67a404a11c803FFFFNRAL