name: CI/CD Pipeline

on:
  push:
    branches: [ "main" , "staging"]
  pull_request:
    branches: [ "main" , "staging"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build -t app:latest .

      - name: Run SonarQube scan
        run: npm run sonar

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy databases
        run: |
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/mongo-service.yaml

      - name: Deploy application
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml

      - name: Apply configuration and autoscaling
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/hpa.yaml